databases:
  - name: mams-db
    databaseName: mams
    plan: free

services:
  - type: web
    name: mams-app
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mams-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: NODE_VERSION
        value: 20.0.0
